#! /bin/sh

# keybind manager
pgrep -x sxhkd > /dev/null || sxhkd -c /home/polarnix/.config/bspwm/sxhkdrc &

# screen size
xrandr --output VGA-0 --mode 1920x1080 &
xrandr --dpi 60 &

# panel
eww reload &
eww open panel &

# wallpaper
nitrogen --restore &

# application launcher
exec albert &

# compositor
xcompmgr &

# workspaces
bspc monitor -d 1 2 3 4 5 6

# wm settings
bspc config border_width 2
bspc config window_gap 10
bspc config normal_border_color "#787C99"
bspc config focused_border_color "#7AA2F7"
bspc config active_border_color "#7AA2F7"
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

# panel spacing
bspc config top_padding 32

# multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# window rules
bspc rule -a albert state=floating focus=on border=off
